"""add cascade delete, indexes, live_session_portfolio fields

Revision ID: 185ad90e988e
Revises: 97323b81fdcc
Create Date: 2026-07-30 14:02:14.869374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '185ad90e988e'
down_revision: Union[str, Sequence[str], None] = '97323b81fdcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backtest_daily_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_backtest_snapshots_rec_target_date', ['backtest_record_id', 'target_type', 'target_id', 'snap_date'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_backtest_daily_snapshots_backtest_record_id_backtest_records'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_backtest_daily_snapshots_backtest_record_id_backtest_records'), 'backtest_records', ['backtest_record_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('backtest_evaluations', schema=None) as batch_op:
        batch_op.create_index('ix_backtest_evaluations_rec_target', ['backtest_record_id', 'target_type', 'target_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_backtest_evaluations_backtest_record_id_backtest_records'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_backtest_evaluations_backtest_record_id_backtest_records'), 'backtest_records', ['backtest_record_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('backtest_records', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_backtest_records_portfolio_strategy_id_portfolio_strategies'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_backtest_records_portfolio_strategy_id_portfolio_strategies'), 'portfolio_strategies', ['portfolio_strategy_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('backtest_trades', schema=None) as batch_op:
        batch_op.create_index('ix_backtest_trades_rec_bar', ['backtest_record_id', 'bar_time'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_backtest_trades_backtest_record_id_backtest_records'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_backtest_trades_backtest_record_id_backtest_records'), 'backtest_records', ['backtest_record_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('formula_signals', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_formula_signals_formula_id_formulas'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_formula_signals_formula_id_formulas'), 'formulas', ['formula_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('live_orders', schema=None) as batch_op:
        batch_op.create_index('ix_live_orders_portfolio', ['portfolio_strategy_id'], unique=False)
        batch_op.create_index('ix_live_orders_session_status', ['live_session_id', 'status'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_live_orders_live_session_id_live_sessions'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_live_orders_live_session_id_live_sessions'), 'live_sessions', ['live_session_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('live_session_portfolios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('circuit_breaker_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_live_session_portfolios_portfolio_strategy_id_portfolio_strategies'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_live_session_portfolios_portfolio_strategy_id_portfolio_strategies'), 'portfolio_strategies', ['portfolio_strategy_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('live_trades', schema=None) as batch_op:
        batch_op.create_index('ix_live_trades_order', ['live_order_id'], unique=False)
        batch_op.create_index('ix_live_trades_portfolio_time', ['portfolio_strategy_id', 'trade_time'], unique=False)
        batch_op.create_index('ix_live_trades_session_time', ['live_session_id', 'trade_time'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_live_trades_live_session_id_live_sessions'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_live_trades_live_session_id_live_sessions'), 'live_sessions', ['live_session_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('portfolio_strategies', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_portfolio_strategies_stock_pool_id_stock_pools'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_portfolio_strategies_stock_pool_id_stock_pools'), 'stock_pools', ['stock_pool_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('stock_pool_stocks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_stock_pool_stocks_pool_id_stock_pools'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_stock_pool_stocks_pool_id_stock_pools'), 'stock_pools', ['pool_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_strategies_portfolio_id_portfolio_strategies'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_strategies_formula_id_formulas'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_strategies_formula_id_formulas'), 'formulas', ['formula_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('fk_strategies_portfolio_id_portfolio_strategies'), 'portfolio_strategies', ['portfolio_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_strategies_portfolio_id_portfolio_strategies'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_strategies_formula_id_formulas'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_strategies_formula_id_formulas'), 'formulas', ['formula_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_strategies_portfolio_id_portfolio_strategies'), 'portfolio_strategies', ['portfolio_id'], ['id'])

    with op.batch_alter_table('stock_pool_stocks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_stock_pool_stocks_pool_id_stock_pools'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_stock_pool_stocks_pool_id_stock_pools'), 'stock_pools', ['pool_id'], ['id'])

    with op.batch_alter_table('portfolio_strategies', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_portfolio_strategies_stock_pool_id_stock_pools'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_portfolio_strategies_stock_pool_id_stock_pools'), 'stock_pools', ['stock_pool_id'], ['id'])

    with op.batch_alter_table('live_trades', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_live_trades_live_session_id_live_sessions'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_live_trades_live_session_id_live_sessions'), 'live_sessions', ['live_session_id'], ['id'])
        batch_op.drop_index('ix_live_trades_session_time')
        batch_op.drop_index('ix_live_trades_portfolio_time')
        batch_op.drop_index('ix_live_trades_order')

    with op.batch_alter_table('live_session_portfolios', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_live_session_portfolios_portfolio_strategy_id_portfolio_strategies'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_live_session_portfolios_portfolio_strategy_id_portfolio_strategies'), 'portfolio_strategies', ['portfolio_strategy_id'], ['id'])
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('circuit_breaker_count')

    with op.batch_alter_table('live_orders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_live_orders_live_session_id_live_sessions'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_live_orders_live_session_id_live_sessions'), 'live_sessions', ['live_session_id'], ['id'])
        batch_op.drop_index('ix_live_orders_session_status')
        batch_op.drop_index('ix_live_orders_portfolio')

    with op.batch_alter_table('formula_signals', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_formula_signals_formula_id_formulas'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_formula_signals_formula_id_formulas'), 'formulas', ['formula_id'], ['id'])

    with op.batch_alter_table('backtest_trades', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_backtest_trades_backtest_record_id_backtest_records'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_backtest_trades_backtest_record_id_backtest_records'), 'backtest_records', ['backtest_record_id'], ['id'])
        batch_op.drop_index('ix_backtest_trades_rec_bar')

    with op.batch_alter_table('backtest_records', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_backtest_records_portfolio_strategy_id_portfolio_strategies'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_backtest_records_portfolio_strategy_id_portfolio_strategies'), 'portfolio_strategies', ['portfolio_strategy_id'], ['id'])

    with op.batch_alter_table('backtest_evaluations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_backtest_evaluations_backtest_record_id_backtest_records'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_backtest_evaluations_backtest_record_id_backtest_records'), 'backtest_records', ['backtest_record_id'], ['id'])
        batch_op.drop_index('ix_backtest_evaluations_rec_target')

    with op.batch_alter_table('backtest_daily_snapshots', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_backtest_daily_snapshots_backtest_record_id_backtest_records'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_backtest_daily_snapshots_backtest_record_id_backtest_records'), 'backtest_records', ['backtest_record_id'], ['id'])
        batch_op.drop_index('ix_backtest_snapshots_rec_target_date')

    # ### end Alembic commands ###
