"""drop nats_request_id from live_orders

Revision ID: 8be6e670ff74
Revises: a1b2c3d4e5f6
Create Date: 2026-08-05 12:40:34.632792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8be6e670ff74'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('live_orders', schema=None) as batch_op:
        batch_op.drop_column('nats_request_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('live_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nats_request_id', sa.VARCHAR(length=64), nullable=True))

    # ### end Alembic commands ###
