"""init 14 tables

Revision ID: 97323b81fdcc
Revises: 
Create Date: 2026-07-29 12:42:53.091736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97323b81fdcc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formulas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('live_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('stopped_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_pools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('formula_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formula_id', sa.Integer(), nullable=False),
    sa.Column('signal_name', sa.String(length=50), nullable=False),
    sa.Column('signal_type', sa.String(length=10), nullable=False),
    sa.Column('trigger_value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['formula_id'], ['formulas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('stock_pool_id', sa.Integer(), nullable=False),
    sa.Column('benchmark_index', sa.String(length=20), nullable=True),
    sa.Column('initial_capital', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('daily_loss_limit', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('max_holdings', sa.Integer(), nullable=True),
    sa.Column('min_commission', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('buy_commission_rate', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('sell_commission_rate', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('stamp_duty_rate', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('slippage', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('trading_session', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['stock_pool_id'], ['stock_pools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_pool_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('stock_code', sa.String(length=20), nullable=False),
    sa.Column('stock_name', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['pool_id'], ['stock_pools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pool_id', 'stock_code')
    )
    op.create_table('backtest_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_strategy_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('params_snapshot', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_strategy_id'], ['portfolio_strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('live_session_portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('portfolio_strategy_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_strategy_id'], ['portfolio_strategies.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['live_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'portfolio_strategy_id')
    )
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('formula_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=5), nullable=False),
    sa.Column('role', sa.String(length=15), nullable=False),
    sa.Column('master_strategy_id', sa.Integer(), nullable=True),
    sa.Column('capital_ratio', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('max_positions', sa.Integer(), nullable=True),
    sa.Column('single_open_ratio', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('stop_loss_ratio', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('take_profit_ratio', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('trailing_stop_ratio', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('add_position_threshold', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('max_add_count', sa.Integer(), nullable=True),
    sa.Column('add_position_ratio', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('reduce_position_ratio', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['formula_id'], ['formulas.id'], ),
    sa.ForeignKeyConstraint(['master_strategy_id'], ['strategies.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio_strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backtest_daily_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backtest_record_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=10), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('snap_date', sa.Date(), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cash', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('market_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('daily_return', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('cumulative_return', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('benchmark_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('positions_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['backtest_record_id'], ['backtest_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backtest_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backtest_record_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=10), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('total_return', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('annual_return', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('volatility', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('sortino_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('calmar_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('win_rate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('profit_factor', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('benchmark_return', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('avg_holding_days', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('var_95', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('cvar_95', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('avg_recovery_days', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('max_recovery_days', sa.Integer(), nullable=True),
    sa.Column('ulcer_index', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('return_stability', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['backtest_record_id'], ['backtest_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backtest_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backtest_record_id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('formula_signal_id', sa.Integer(), nullable=True),
    sa.Column('signal_name', sa.String(length=50), nullable=False),
    sa.Column('signal_type', sa.String(length=15), nullable=False),
    sa.Column('stock_code', sa.String(length=20), nullable=False),
    sa.Column('trade_type', sa.String(length=4), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('commission', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stamp_duty', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('bar_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['backtest_record_id'], ['backtest_records.id'], ),
    sa.ForeignKeyConstraint(['formula_signal_id'], ['formula_signals.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('live_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('live_session_id', sa.Integer(), nullable=False),
    sa.Column('portfolio_strategy_id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('stock_code', sa.String(length=20), nullable=False),
    sa.Column('trade_type', sa.String(length=4), nullable=False),
    sa.Column('order_type', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('filled_quantity', sa.Integer(), nullable=True),
    sa.Column('filled_price', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('nats_request_id', sa.String(length=64), nullable=True),
    sa.Column('signal_name', sa.String(length=50), nullable=True),
    sa.Column('signal_type', sa.String(length=15), nullable=True),
    sa.Column('bar_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['live_session_id'], ['live_sessions.id'], ),
    sa.ForeignKeyConstraint(['portfolio_strategy_id'], ['portfolio_strategies.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('live_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('live_session_id', sa.Integer(), nullable=False),
    sa.Column('live_order_id', sa.Integer(), nullable=True),
    sa.Column('portfolio_strategy_id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('stock_code', sa.String(length=20), nullable=False),
    sa.Column('trade_type', sa.String(length=4), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('commission', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stamp_duty', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('trade_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['live_order_id'], ['live_orders.id'], ),
    sa.ForeignKeyConstraint(['live_session_id'], ['live_sessions.id'], ),
    sa.ForeignKeyConstraint(['portfolio_strategy_id'], ['portfolio_strategies.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('live_trades')
    op.drop_table('live_orders')
    op.drop_table('backtest_trades')
    op.drop_table('backtest_evaluations')
    op.drop_table('backtest_daily_snapshots')
    op.drop_table('strategies')
    op.drop_table('live_session_portfolios')
    op.drop_table('backtest_records')
    op.drop_table('stock_pool_stocks')
    op.drop_table('portfolio_strategies')
    op.drop_table('formula_signals')
    op.drop_table('stock_pools')
    op.drop_table('live_sessions')
    op.drop_table('formulas')
    # ### end Alembic commands ###
