"""add formula_count to formulas

Revision ID: a5b351e0d6d7
Revises: f3417686e6fb
Create Date: 2026-08-10 16:30:29.076123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5b351e0d6d7'
down_revision: Union[str, Sequence[str], None] = 'f3417686e6fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('formulas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('formula_count', sa.Integer(), server_default='200', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('formulas', schema=None) as batch_op:
        batch_op.drop_column('formula_count')

    # ### end Alembic commands ###
