"""add data integrity constraints (#18/#19/#20/#21)

Revision ID: d4a5b6c7d8e9
Revises: a5b351e0d6d7
Create Date: 2026-08-11 19:00:00.000000

- #18: strategies.master_strategy_id 自引用 FK 补 ondelete=RESTRICT
- #19: stock_pools.code 补 UNIQUE
- #20: FK/查询列补索引（约 13 处）
- #21: 26 列补 server_default 并收紧 NOT NULL
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4a5b6c7d8e9'
down_revision: Union[str, Sequence[str], None] = 'a5b351e0d6d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # #19 股票池 code 唯一（SQLite batch 重建 3 行小表）
    with op.batch_alter_table('stock_pools', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_stock_pools_code'), ['code'])

    # #18/#20/#21 strategies：自引用 FK RESTRICT + 3 索引 + 10 列 server_default/NOT NULL
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.create_index('ix_strategies_portfolio_id', ['portfolio_id'], unique=False)
        batch_op.create_index('ix_strategies_formula_id', ['formula_id'], unique=False)
        batch_op.create_index('ix_strategies_master_strategy_id', ['master_strategy_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_strategies_master_strategy_id_strategies'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_strategies_master_strategy_id_strategies'), 'strategies', ['master_strategy_id'], ['id'], ondelete='RESTRICT')
        batch_op.alter_column('capital_ratio', server_default='0.6000', nullable=False)
        batch_op.alter_column('max_positions', server_default='5', nullable=False)
        batch_op.alter_column('single_open_ratio', server_default='0.1000', nullable=False)
        batch_op.alter_column('stop_loss_ratio', server_default='0.0500', nullable=False)
        batch_op.alter_column('take_profit_ratio', server_default='0.1500', nullable=False)
        batch_op.alter_column('trailing_stop_ratio', server_default='0.0300', nullable=False)
        batch_op.alter_column('add_position_threshold', server_default='0.0500', nullable=False)
        batch_op.alter_column('max_add_count', server_default='2', nullable=False)
        batch_op.alter_column('add_position_ratio', server_default='0.1000', nullable=False)
        batch_op.alter_column('reduce_position_ratio', server_default='0.3000', nullable=False)

    # #20/#21 portfolio_strategies：stock_pool_id 索引 + 12 列 server_default/NOT NULL
    with op.batch_alter_table('portfolio_strategies', schema=None) as batch_op:
        batch_op.create_index('ix_portfolio_strategies_stock_pool_id', ['stock_pool_id'], unique=False)
        batch_op.alter_column('benchmark_index', server_default='000300.SH', nullable=False)
        batch_op.alter_column('initial_capital', server_default='500000', nullable=False)
        batch_op.alter_column('max_drawdown', server_default='0.2000', nullable=False)
        batch_op.alter_column('daily_loss_limit', server_default='0.0500', nullable=False)
        batch_op.alter_column('max_holdings', server_default='10', nullable=False)
        batch_op.alter_column('min_commission', server_default='5', nullable=False)
        batch_op.alter_column('buy_commission_rate', server_default='0.000250', nullable=False)
        batch_op.alter_column('sell_commission_rate', server_default='0.000250', nullable=False)
        batch_op.alter_column('stamp_duty_rate', server_default='0.000500', nullable=False)
        batch_op.alter_column('slippage', server_default='0', nullable=False)
        batch_op.alter_column('trading_session', server_default='full', nullable=False)
        batch_op.alter_column('status', server_default='active', nullable=False)

    # #20/#21 live_orders：strategy_id/stock_code 索引 + filled_quantity server_default/NOT NULL
    with op.batch_alter_table('live_orders', schema=None) as batch_op:
        batch_op.create_index('ix_live_orders_strategy_id', ['strategy_id'], unique=False)
        batch_op.create_index('ix_live_orders_stock_code', ['stock_code'], unique=False)
        batch_op.alter_column('filled_quantity', server_default='0', nullable=False)

    # #20/#21 backtest_records：portfolio_strategy_id 索引 + progress server_default/NOT NULL
    with op.batch_alter_table('backtest_records', schema=None) as batch_op:
        batch_op.create_index('ix_backtest_records_portfolio_strategy_id', ['portfolio_strategy_id'], unique=False)
        batch_op.alter_column('progress', server_default='0', nullable=False)

    # #21 live_session_portfolios：status/circuit_breaker_count server_default/NOT NULL
    with op.batch_alter_table('live_session_portfolios', schema=None) as batch_op:
        batch_op.alter_column('status', server_default='active', nullable=False)
        batch_op.alter_column('circuit_breaker_count', server_default='0', nullable=False)

    # #20 formula_signals：formula_id 索引
    with op.batch_alter_table('formula_signals', schema=None) as batch_op:
        batch_op.create_index('ix_formula_signals_formula_id', ['formula_id'], unique=False)

    # #20 backtest_trades：strategy_id/formula_signal_id 索引（ondelete 有意保留不动）
    with op.batch_alter_table('backtest_trades', schema=None) as batch_op:
        batch_op.create_index('ix_backtest_trades_strategy_id', ['strategy_id'], unique=False)
        batch_op.create_index('ix_backtest_trades_formula_signal_id', ['formula_signal_id'], unique=False)

    # #20 live_trades：strategy_id/stock_code 索引
    with op.batch_alter_table('live_trades', schema=None) as batch_op:
        batch_op.create_index('ix_live_trades_strategy_id', ['strategy_id'], unique=False)
        batch_op.create_index('ix_live_trades_stock_code', ['stock_code'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('live_trades', schema=None) as batch_op:
        batch_op.drop_index('ix_live_trades_stock_code')
        batch_op.drop_index('ix_live_trades_strategy_id')

    with op.batch_alter_table('backtest_trades', schema=None) as batch_op:
        batch_op.drop_index('ix_backtest_trades_formula_signal_id')
        batch_op.drop_index('ix_backtest_trades_strategy_id')

    with op.batch_alter_table('formula_signals', schema=None) as batch_op:
        batch_op.drop_index('ix_formula_signals_formula_id')

    with op.batch_alter_table('live_session_portfolios', schema=None) as batch_op:
        batch_op.alter_column('circuit_breaker_count', nullable=True)
        batch_op.alter_column('status', nullable=True)

    with op.batch_alter_table('backtest_records', schema=None) as batch_op:
        batch_op.alter_column('progress', nullable=True)
        batch_op.drop_index('ix_backtest_records_portfolio_strategy_id')

    with op.batch_alter_table('live_orders', schema=None) as batch_op:
        batch_op.alter_column('filled_quantity', nullable=True)
        batch_op.drop_index('ix_live_orders_stock_code')
        batch_op.drop_index('ix_live_orders_strategy_id')

    with op.batch_alter_table('portfolio_strategies', schema=None) as batch_op:
        batch_op.alter_column('status', nullable=True)
        batch_op.alter_column('trading_session', nullable=True)
        batch_op.alter_column('slippage', nullable=True)
        batch_op.alter_column('stamp_duty_rate', nullable=True)
        batch_op.alter_column('sell_commission_rate', nullable=True)
        batch_op.alter_column('buy_commission_rate', nullable=True)
        batch_op.alter_column('min_commission', nullable=True)
        batch_op.alter_column('max_holdings', nullable=True)
        batch_op.alter_column('daily_loss_limit', nullable=True)
        batch_op.alter_column('max_drawdown', nullable=True)
        batch_op.alter_column('initial_capital', nullable=True)
        batch_op.alter_column('benchmark_index', nullable=True)
        batch_op.drop_index('ix_portfolio_strategies_stock_pool_id')

    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.alter_column('reduce_position_ratio', nullable=True)
        batch_op.alter_column('add_position_ratio', nullable=True)
        batch_op.alter_column('max_add_count', nullable=True)
        batch_op.alter_column('add_position_threshold', nullable=True)
        batch_op.alter_column('trailing_stop_ratio', nullable=True)
        batch_op.alter_column('take_profit_ratio', nullable=True)
        batch_op.alter_column('stop_loss_ratio', nullable=True)
        batch_op.alter_column('single_open_ratio', nullable=True)
        batch_op.alter_column('max_positions', nullable=True)
        batch_op.alter_column('capital_ratio', nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_strategies_master_strategy_id_strategies'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_strategies_master_strategy_id_strategies'), 'strategies', ['master_strategy_id'], ['id'])
        batch_op.drop_index('ix_strategies_master_strategy_id')
        batch_op.drop_index('ix_strategies_formula_id')
        batch_op.drop_index('ix_strategies_portfolio_id')

    with op.batch_alter_table('stock_pools', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_stock_pools_code'), type_='unique')

    # ### end Alembic commands ###
