"""add order_ref to live_orders

Revision ID: f3417686e6fb
Revises: 8be6e670ff74
Create Date: 2026-08-10 15:47:38.416417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3417686e6fb'
down_revision: Union[str, Sequence[str], None] = '8be6e670ff74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('live_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_ref', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('bridge_order_id', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###
    # status 值域迁移：切片4 旧值 accepted ≈ filled（首期受理即成交），收编进新状态机
    op.execute("UPDATE live_orders SET status='filled' WHERE status='accepted'")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("UPDATE live_orders SET status='accepted' WHERE status='filled'")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('live_orders', schema=None) as batch_op:
        batch_op.drop_column('bridge_order_id')
        batch_op.drop_column('order_ref')

    # ### end Alembic commands ###
